/*!40101 SET NAMES utf8*/;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0*/;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0*/;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO'*/;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0*/;
CREATE DATABASE /*!32312 IF NOT EXISTS*/university_student_database /*!40100 DEFAULT CHARACTER SET latin1*/;


USE university_student_database;

DROP TABLE IF EXISTS students;
CREATE TABLE students(
   id                                 INTEGER  NOT NULL PRIMARY KEY 
  ,name                               VARCHAR(19) NOT NULL
  ,university                         VARCHAR(37) NOT NULL
  ,program                            VARCHAR(13) NOT NULL
  ,specialisation                     VARCHAR(51) NOT NULL
  ,semester                           VARCHAR(3) NOT NULL
);

INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (0,'Camila Wood','Stanford University','B.Com','Honours','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (1,'Alexander Thompson','Stanford University','B.Com','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (2,'Liam Taylor','Harvard University','B.Com','Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (3,'Evelyn Jenkins','Stanford University','B.Com','Honours','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (4,'Michael Jackson','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (5,'Chloe Moore','Stanford University','B.Com','Honours','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (6,'Nicholas Clark','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (7,'Olivia Richardson','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (8,'Aiden Rivera','Stanford University','B.Com','Honours','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (9,'Harper Turner','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (10,'Madison Lee','Stanford University','BBA','Business Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (11,'Carter Hall','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (12,'Mia Thomas','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (13,'Lucas Evans','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (14,'Abigail Bailey','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (15,'Joseph Diaz','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (16,'William Walker','University of Cambridge','MBA','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (17,'Andrew Anderson','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (18,'Sophia King','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (19,'Avery Gonzalez','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (20,'Lily Davis','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (21,'Scarlett Cooper','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (22,'Grace Reed','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (23,'Matthew Johnson','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (24,'Jackson Baker','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (25,'Ella Martinez','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (26,'Henry Perez','Stanford University','B.Com','Honours','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (27,'Ava White','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (28,'Gabriel Miller','Stanford University','B.Com','Honours','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (29,'Mia Brown','Stanford University','BBA','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (30,'Layla Garcia','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (31,'Emma Stewart','Stanford University','BBA','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (32,'Daniel Adams','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (33,'Logan Smith','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (34,'James Harris','Stanford University','B.Com','Accounting','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (35,'Benjamin Martin','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (36,'Elijah Robinson','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (37,'Zoey Hayes','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (38,'Samuel Phillips','Harvard University','B.Com','Business Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (39,'Emily Williams','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (40,'Sofia Lewis','Stanford University','BBA','Financial Services','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (41,'Amelia Young','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (42,'Charlotte Wilson','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (43,'Jack Scott','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (44,'Noah Parker','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (45,'David Rodriguez','Harvard University','MBA','Business Analytics','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (46,'Aria Nelson','Stanford University','B.Com','Honours','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (47,'Ethan Carter','Harvard University','B.Com','Business Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (48,'Oliver Green','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (49,'Harper Jones','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (50,'David Martin','Stanford University','BBA','Business Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (51,'Avery Green','Stanford University','BBA','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (52,'Aiden Wood','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (53,'Jackson Anderson','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (54,'Scarlett Lee','Stanford University','BBA','Finance','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (55,'Lucas Johnson','Stanford University','MBA','Digital Marketing','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (56,'Madison Davis','Massachusetts Institute of Technology','BBA','Digital Marketing','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (57,'Nicholas Jones','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (58,'Evelyn Stewart','Stanford University','BBA','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (59,'Benjamin Richardson','Stanford University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (60,'Charlotte Walker','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (61,'Samuel Scott','Harvard University','B.Com','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (62,'William Rodriguez','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (63,'Emily Carter','Harvard University','B.Com','Business Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (64,'Carter Hall','Harvard University','Intg. BBA+MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (65,'Alexander Moore','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (66,'Emma Wilson','Massachusetts Institute of Technology','BBA','Digital Marketing','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (67,'Mia Young','Harvard University','B.Com','Financial Services with Digital Finance','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (68,'Aria Evans','Stanford University','BBA','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (69,'Layla Phillips','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (70,'Matthew Lewis','Massachusetts Institute of Technology','BBA','Digital Marketing','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (71,'Noah Jenkins','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (72,'Camila Hayes','Harvard University','MBA','Entrepreneurship & Innovation','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (73,'Logan Turner','Stanford University','B.Com','Finance','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (74,'Lily Miller','Harvard University','B.Com','Financial Services with Digital Finance','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (75,'Mia Perez','Harvard University','B.Com','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (76,'Zoey Rivera','Stanford University','MBA','Banking and Financial Services','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (77,'Sophia King','Stanford University','MBA','Digital Marketing','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (78,'Grace Cooper','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (79,'Chloe Williams','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (80,'Ella Bailey','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (81,'Harper Nelson','Stanford University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (82,'Henry Baker','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (83,'Andrew Gonzalez','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (84,'Amelia Harris','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (85,'Abigail Robinson','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (86,'Harper Jackson','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (87,'Michael White','Massachusetts Institute of Technology','BBA','Digital Marketing','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (88,'Daniel Brown','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (89,'Elijah Thomas','Harvard University','MBA','Entrepreneurship & Innovation','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (90,'Liam Thompson','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (91,'Joseph Martinez','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (92,'James Taylor','Massachusetts Institute of Technology','BBA','Digital Marketing','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (93,'Ava Clark','Massachusetts Institute of Technology','BBA','Digital Marketing','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (94,'Gabriel Diaz','Harvard University','B.Com','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (95,'Oliver Parker','California Institute of Technology','BBA','Brand Management','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (96,'Olivia Smith','Harvard University','B.Com','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (97,'Ethan Adams','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (98,'Sofia Garcia','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (99,'Jack Reed','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (100,'Henry Gonzalez','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (101,'Jackson Johnson','Harvard University','B.Com','Financial Services with Digital Finance','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (102,'William Richardson','California Institute of Technology','BBA','Brand Management','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (103,'Gabriel Wilson','Imperial College London','BBA','Entrepreneurship & Innovation','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (104,'Ava Walker','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (105,'Harper Bailey','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (106,'Alexander Clark','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (107,'Michael Evans','Stanford University','B.Com','Finance','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (108,'Zoey Jenkins','Stanford University','B.Com','Business Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (109,'Liam Taylor','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (110,'Camila Rivera','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (111,'Jack Garcia','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (112,'Joseph Parker','Massachusetts Institute of Technology','BBA','Digital Marketing','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (113,'Abigail Thomas','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (114,'Sophia Carter','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (115,'Layla Jackson','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (116,'Mia Smith','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (117,'Sofia Nelson','Stanford University','B.Com','Business Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (118,'Elijah Williams','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (119,'Charlotte Baker','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (120,'Benjamin Green','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (121,'Matthew Miller','Harvard University','B.Com','Information Technology with Accounting Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (122,'Ella Stewart','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (123,'Emily Moore','Stanford University','BBA','Finance','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (124,'Noah Martinez','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (125,'Grace Hall','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (126,'Logan Brown','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (127,'Lily Davis','Stanford University','BBA','Business Analytics','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (128,'Amelia Jones','Massachusetts Institute of Technology','BBA','Digital Marketing','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (129,'Carter Wood','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (130,'Emma Reed','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (131,'Harper Diaz','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (132,'Daniel Lee','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (133,'David Adams','Stanford University','BBA','Business Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (134,'James Scott','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (135,'Chloe Anderson','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (136,'Oliver Turner','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (137,'Scarlett Cooper','University of Oxford','Intg. BBA+MBA','Business Analytics','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (138,'Mia Young','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (139,'Olivia White','Harvard University','B.Com','Business Analytics','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (140,'Lucas Hayes','Stanford University','B.Com','Honours','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (141,'Aria King','University of Cambridge','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (142,'Madison Harris','Harvard University','MBA','Brand Management','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (143,'Aiden Thompson','University of Oxford','Intg. BBA+MBA','Financial Services','9th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (144,'Andrew Phillips','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (145,'Evelyn Robinson','Harvard University','MBA','Innovation Entrepreneurship and Venture Development','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (146,'Avery Lewis','Stanford University','BBA','Financial Services','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (147,'Ethan Martin','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (148,'Nicholas Rodriguez','Harvard University','MBA','International Business','3rd');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (149,'Samuel Perez','Stanford University','BBA','International Business','5th');
INSERT INTO students(id,name,university,program,specialisation,semester) VALUES (150,'Emily Lee','Massachusetts Institute of Technology','BBA','Digital Marketing','5th');
